### ISSUE TITLE
I was thinking about adding dynamic username and password function.

### ISSUE THREAD

**Issue by elico** [fangdingjun/socks-go#1]
I have seen the code at:
- <https://github.com/fangdingjun/socks-go/blob/master/socks5.go#L172>

And I think it's possible to enhance this service with authentication and\or authorization mechanism.
- Authorization ie based on IP acl that will match the src address to a whitelist
- Authentication ie a function that will know to match the incomming connection username and password against some simple mechanism like htaccess\sqlite\redis\msysql.

**Comment by fangdingjun** [comment]
@elico 
That's great! Could you help to implement this?

**Comment by elico** [comment]
@fangdingjun a library would be good enough?
If you have some functions specs I might be able to write a library that will work with couple options suchas:
- mysql/mariadb
- LDAP
- htacesss (auto reload on change)
...

**Comment by fangdingjun** [comment]
now, i add a AuthService  interface,

implement yourself auth service can do what you want base on username, password and user's  source 
 ip and port

```
type AuthService interface {
	Authenticate(username, password string, addr net.Addr) bool
}
type Conn struct {
	net.Conn
	Dial DialFunc
	Auth AuthService
}

```

example
```
s := Conn{Conn: conn, Auth: &passwordAuth{user, pass}}
s.Serve()
```

**Comment by elico** [comment]
@fangdingjun Thanks!
