### ISSUE TITLE
But I can't add login and password to my code.

### ISSUE THREAD

**Issue by sdima75** [fangdingjun/socks-go#2]
Hello.
Thank you for your code.
I am not a programmer. But I sometimes make small programs for myself. I like your code and without password my program works.

I looked at all your files and tests. But I can't add login and password to my code.
How do I add login and password to server and client (I haven't tried it in client yet because I don't have a working server with password)?

```
func main() {
	user := "admin"
	pass := "pass"
```
...
`s := socks.Conn{Conn: c, Dial: d.Dial, Auth: &passwordAuth{user, pass}}`
err - undeclared name: passwordAuthcompiler

This doesn't work either and other different options:
`s := socks.Conn{Conn: c, Dial: d.Dial, Auth: socks.AuthService.Authenticate(user, pass, conn)}`

Thanks for your help!

**Comment by fangdingjun** [comment]
You can implement youself password auth service, by implement socks.AuthService interface

example
    
    type MyAuthService struct{}
    func (a *MyAuthService) Authenticate(username, password string, addr net.Addr) bool{
       // do something to auth user 
       return true   // auth success
       // return false // auth fail
    }

    // active auth service
    s := socks.Conn{Conn: c, Dial: d.Dial, Auth: &MyAuthService{}}


or you can use the default password auth service(update to  00415c617  first)
     
       s := socks.Conn{Conn: c, Dial: d.Dial, Auth: &socks.PasswordAuth{user, pass}}

**Comment by sdima75** [comment]
Hello.
Thank you for your reply.
I have updated the repository. (a simple -u update, and then I deleted the repository folder and I installed your repository again.)

This code works:

```package main

import (
	"log"
	"net"
	"time"

	socks "github.com/fangdingjun/socks-go"
)

type MyAuthService struct {
}

func (a *MyAuthService) Authenticate(username, password string, addr net.Addr) bool {
	if username == "admin" && password == "pass" {
		return true
	} else {
		return false
	}
}

func main() {
	// conn, err := net.Listen("tcp", ":1080")
	conn, err := net.Listen("tcp", ":1080")
	if err != nil {
		log.Fatal("Err global: ", err)
	}

	for {
		c, err := conn.Accept()
		if err != nil {
			log.Println(err)
			continue
		}

		log.Printf("connected from %s", c.RemoteAddr())

		d := net.Dialer{Timeout: 10 * time.Second}
		s := socks.Conn{Conn: c, Dial: d.Dial, Auth: &MyAuthService{}}

		go s.Serve()
	}
}
```

This code does not work. 
Can you please tell me what I am doing wrong?
```
package main

import (
	"log"
	"net"
	"time"

	socks "github.com/fangdingjun/socks-go"
)

func main() {
	user := "admin"
	pass := "pass"

	conn, err := net.Listen("tcp", ":1080")
	if err != nil {
		log.Fatal("Err global: ", err)
	}

	for {
		c, err := conn.Accept()
		if err != nil {
			log.Println(err)
			continue
		}

		log.Printf("connected from %s", c.RemoteAddr())

		d := net.Dialer{Timeout: 10 * time.Second}
		s := socks.Conn{Conn: c, Dial: d.Dial, Auth: &socks.PasswordAuth{user, pass}} //too many values in struct literalco
		go s.Serve()
	}
}
```
```
package main

import (
	"log"
	"net"
	"time"

	socks "github.com/fangdingjun/socks-go"
)

func main() {
	// a := socks.PasswordAuth {username: "admin", password: "pass"} //unknown field username in struct literalc
	var a socks.PasswordAuth = socks.PasswordAuth{"admin", "pass"} //too many values in struct literalcompiler

	conn, err := net.Listen("tcp", ":1080")
	if err != nil {
		log.Fatal("Err global: ", err)
	}

	for {
		c, err := conn.Accept()
		if err != nil {
			log.Println(err)
			continue
		}

		log.Printf("connected from %s", c.RemoteAddr())

		d := net.Dialer{Timeout: 10 * time.Second}
		s := socks.Conn{Conn: c, Dial: d.Dial, Auth: &a}
		go s.Serve()
	}
}
```
Thanks for your help!

**Comment by fangdingjun** [comment]
I forgot to export the struct field of PasswordAuth, 

update to latest commit,  this code may works

       a := socks.PasswordAuth {Username: "admin", Password: "pass"}

**Comment by sdima75** [comment]
Hello.
Everything works! Thank you for your help!
I hope your answers will also help other users!

I have a suggestion:
In the client.go file on line #80 - `return fmt.Errorf("password rejected")`
Replace the text with - `"Login or password rejected."`
This code works when the password is wrong or the login is wrong.

Once again - Thank you for your help!
